Added project overview, features and contributors to README
zuri-training/Proj-CC_gen-Team-124 pull request #13
Opened 2022-07-27 21:51 UTC by ayobami11

Updated README.md file to include more information about the project.

2022-07-28 10:34 UTC, whitesoftx requested changes
App name is Credard, not Credicard. 

The [Documentation for Project Presentation](https://docs.google.com/document/d/1DWA4ZwdISgN0JvuIN36B516YIxWYqzoncjOXI4zbpQM/) content has changes, you should effect it for now.

2022-07-28 14:12 UTC, ayobami11 commented
Should I replace the current readme content with the documentation for the project presentation?

2022-07-29 20:30 UTC, VictoriaAde approved these changes
Hi, @ayobami11 

# Approved 
You have done a good job on this documentaion.
Good job :100: :clap:

2022-07-29 20:41 UTC, whitesoftx approved these changes

2022-07-29 20:41 UTC, merged